version: "3"
services:
  database:
    env_file: "./_docker-compose-env/database.env"
    ports:
      - "27017:27017"
    build:
      dockerfile: dockerfile
      context: ./database
  server:
    env_file: "./_docker-compose-env/server.env"
    depends_on:
      - database
    build:
      dockerfile: dockerfile.dev
      context: ./server
    ports:
      - "3000:3000"
    # For development
    volumes:
      - ./server/src:/root/app/src
      - /root/app/node_modules
